# Ex2 - Filtering and Sorting Data

## Learning Objectives
In this exercise, you will learn:
- How to load data directly from the internet
- Display options for better data visualization
- Advanced filtering techniques with `.isin()`
- Column slicing with `.iloc[]`
- Working with multiple columns and specific rows

This time we are going to pull data directly from the internet.

### Step 1. Import the necessary libraries

**Explanation:**  
We import the essential libraries for data analysis:

- **`numpy`**: Provides numerical computing capabilities and array operations
- **`pandas`**: The main library for data manipulation and analysis

**Standard aliases:**
- `np` for numpy
- `pd` for pandas

These aliases are universally recognized in the Python data science community.

In [1]:
import numpy as np
import pandas as pd

### Step 2. Set display options for better visualization

**Explanation:**  
`pd.set_option()` configures how pandas displays DataFrames in your output.

**What this specific setting does:**
- **`'display.max_columns'`**: Controls how many columns are shown
- **`None`**: Shows **ALL columns** without truncation

**Default behavior without this setting:**
- Pandas truncates the display when there are many columns
- Shows first few columns, then `...`, then last few columns
- Example: `Column1, Column2, ..., Column34, Column35`

**After setting to None:**
- All columns are displayed side by side
- Better for datasets with moderate number of columns (like this one with 35 columns)

**Other useful display options:**
- `'display.max_rows'` - Control how many rows to show
- `'display.width'` - Control the width of the display
- `'display.precision'` - Control decimal places for floats

**When to use:**  
Use this at the beginning of notebooks when you want to see all columns in your analysis.

In [14]:
pd.set_option('display.max_columns', None) 

# This is done to have all columns displayed afterwards when displaying the DATA

### Step 3. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv)

**Explanation:**  
`pd.read_csv()` can read CSV files directly from the internet using a URL.

**Key points:**
- No need to download the file first
- Pandas automatically handles the HTTP request
- The file is loaded directly into memory as a DataFrame
- This is a **CSV (Comma-Separated Values)** file, so no special separator needed

**Dataset information:**
- Contains statistics from the UEFA Euro 2012 football tournament
- Each row represents one national team
- Columns include: goals, shots, passes, tackles, fouls, cards, etc.

**Comparison with previous exercise:**
- Chipotle exercise: Used TSV file (tab-separated) → needed `sep='\t'`
- This exercise: Uses CSV file (comma-separated) → default separator works

In [3]:
euro12 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv')

### Step 4. Display the DataFrame

**Explanation:**  
Simply typing the variable name displays the entire DataFrame.

**What you'll see:**
- 16 rows (one for each team in Euro 2012)
- 35 columns (various statistics)
- All columns visible because we set `display.max_columns` to `None`

**Note on the display:**  
Because we configured pandas to show all columns, this output will be very wide. This is useful for exploration but might not fit well on narrow screens.

In [15]:
euro12

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0,9,9,18

**Expected Output (abbreviated view):**
```
                  Team  Goals  Shots on target  Shots off target  ... Yellow Cards  Red Cards  Subs on  Subs off  Players Used
0              Croatia      4               13                12  ...            9          0        9         9            16
1       Czech Republic      4               13                18  ...            7          0       11        11            19
2              Denmark      4               10                10  ...            4          0       15        15            23
3              England      5               11                18  ...            5          0       11        11            16
4               France      3               22                24  ...            6          0       11        11            19
5              Germany     10               32                32  ...            4          0       14        14            17
6               Greece      5                8                18  ...            9          1       12        12            20
7                Italy      6               34                45  ...           16          0       18        18            23
8          Netherlands      2               12                36  ...            5          0        12        12            17
9               Poland      2               15                23  ...            7          1        12        12            17
10            Portugal      6               22                42  ...           12          0       16        16            20
11 Republic of Ireland      1                7                12  ...            6          1       10        10            17
12              Russia      5                9                31  ...            6          0       11        11            16
13               Spain     12               42                33  ...           11          0       17        17            18
14              Sweden      5               17                19  ...            7          0       14        14            22
15             Ukraine      2                7                26  ...            5          0       13        13            18

[16 rows x 35 columns]
```

### Step 5. Display only the first 10 rows

**Explanation:**  
`.head(10)` shows only the first 10 rows of the DataFrame.

**Why use `.head()`?**
- Quick inspection of data structure
- Faster to render than the full dataset
- Shows column names and sample data

**Variations:**
- `.head()` with no argument → shows first **5 rows** (default)
- `.head(10)` → shows first **10 rows**
- `.head(n)` → shows first **n rows**

**Related methods:**
- `.tail(n)` → shows last n rows
- `.sample(n)` → shows n random rows

In [ ]:
euro12.head(10) #First 10 rows display

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1,7,7,17

**Expected Output (first 10 teams):**
```
                  Team  Goals  Shots on target  Shots off target  ... Yellow Cards  Red Cards  Subs on  Subs off  Players Used
0              Croatia      4               13                12  ...            9          0        9         9            16
1       Czech Republic      4               13                18  ...            7          0       11        11            19
2              Denmark      4               10                10  ...            4          0       15        15            23
3              England      5               11                18  ...            5          0       11        11            16
4               France      3               22                24  ...            6          0       11        11            19
5              Germany     10               32                32  ...            4          0       14        14            17
6               Greece      5                8                18  ...            9          1       12        12            20
7                Italy      6               34                45  ...           16          0       18        18            23
8          Netherlands      2               12                36  ...            5          0       12        12            17
9               Poland      2               15                23  ...            7          1       12        12            17

[10 rows x 35 columns]
```

### Step 6. Get DataFrame information

**Explanation:**  
`.info()` provides a comprehensive summary of the DataFrame structure.

**Information displayed:**
1. **DataFrame type**: Confirms it's a pandas DataFrame
2. **Index information**: RangeIndex from 0 to 15 (16 teams)
3. **Column count**: 35 columns total
4. **Column details for each column:**
   - Column name
   - Non-null count (helps identify missing data)
   - Data type (int64, object, float64, etc.)
5. **Data type summary**: How many columns of each type
6. **Memory usage**: How much RAM the DataFrame uses

**Data types explained:**
- **`int64`**: Integer numbers (whole numbers)
- **`object`**: Strings/text or mixed types
- **`float64`**: Decimal numbers (if present)

**Use cases:**
- Check for missing data (Non-Null Count vs total rows)
- Verify data types before operations
- Estimate memory requirements
- Quick overview of dataset structure

In [ ]:
euro12.info() # Provides a comprehensive summary of the DataFrame structure

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Team                        16 non-null     object
 1   Goals                       16 non-null     int64
 2   Shots on target             16 non-null     int64
 3   Shots off target            16 non-null     int64
 4   Shooting Accuracy           16 non-null     object
 5   % Goals-to-shots            16 non-null     object
 6   Total shots (inc. Blocked)  16 non-null     int64
 7   Hit Woodwork                16 non-null     int64
 8   Penalty goals               16 non-null     int64
 9   Penalties not scored        16 non-null     int64
 10  Headed goals                16 non-null     int64
 11  Passes                      16 non-null     int64
 12  Passes completed            16 non-null     int64
 13  Passing Accuracy            16 non-null     object
 14  Touches                     16 non-null     int64
 15  Crosses                     16 non-null     int64
 16  Dribbles                    16 non-null     int64
 17  Corners Taken               16 non-null     int64
 18  Tackles                     16 non-null     int64
 19  Clearances                  16 non-null     int64
 20  Interceptions               16 non-null     int64
 21  Clearances off line         15 non-null     float64
 22  Clean Sheets                16 non-null     int64
 23  Blocks                      16 non-null     int64
 24  Goals conceded              16 non-null     int64
 25  Saves made                  16 non-null     int64
 26  Saves-to-shots ratio        16 non-null     object
 27  Fouls Won                   16 non-null     int64
 28  Fouls Conceded              16 non-null     int64
 29  Offsides                    16 non-null     int64
 30  Yellow Cards                16 non-null     int64
 31  Red Cards                   16 non-null     int64
 32  Subs on                     16 non-null     int64
 33  Subs off                    16 non-null     int64
 34  Players Used                16 non-null     int64
dtypes: float64(1), int64(29), object(5)
memory usage: 4.5+ KB

**Expected Output:**
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Team                        16 non-null     object
 1   Goals                       16 non-null     int64 
 2   Shots on target             16 non-null     int64 
 3   Shots off target            16 non-null     int64 
 4   Shooting Accuracy           16 non-null     object
 5   % Goals-to-shots            16 non-null     object
 6   Total shots (inc. Blocked)  16 non-null     int64 
 7   Hit Woodwork                16 non-null     int64 
 8   Penalty goals               16 non-null     int64 
 9   Penalties not scored        16 non-null     int64 
 10  Headed goals                16 non-null     int64 
 11  Passes                      16 non-null     int64 
 12  Passes completed            16 non-null     int64 
 13  Passing Accuracy            16 non-null     object
 14  Touches                     16 non-null     int64 
 15  Crosses                     16 non-null     int64 
 16  Dribbles                    16 non-null     int64 
 17  Corners Taken               16 non-null     int64 
 18  Tackles                     16 non-null     int64 
 19  Clearances                  16 non-null     int64 
 20  Interceptions               16 non-null     int64 
 21  Clearances off line         15 non-null     float64
 22  Clean Sheets                16 non-null     int64 
 23  Blocks                      16 non-null     int64 
 24  Goals conceded              16 non-null     int64 
 25  Saves made                  16 non-null     int64 
 26  Saves-to-shots ratio        16 non-null     object
 27  Fouls Won                   16 non-null     int64 
 28  Fouls Conceded              16 non-null     int64 
 29  Offsides                    16 non-null     int64 
 30  Yellow Cards                16 non-null     int64 
 31  Red Cards                   16 non-null     int64 
 32  Subs on                     16 non-null     int64 
 33  Subs off                    16 non-null     int64 
 34  Players Used                16 non-null     int64 
dtypes: float64(1), int64(29), object(5)
memory usage: 4.5+ KB
```

**Key observations:**
- 16 rows (teams) and 35 columns (statistics)
- Most columns are integers (29 columns)
- Some percentage columns are stored as 'object' (strings) because of the '%' symbol
- 'Clearances off line' has 15 non-null values (1 missing value)

### Step 7. Display the shape of the DataFrame

**Explanation:**  
`.shape` is an **attribute** (not a method) that returns the dimensions of the DataFrame.

**Returns:**  
A tuple in the format `(rows, columns)`

**Example:**  
`(16, 35)` means:
- **16 rows** (teams)
- **35 columns** (statistics)

**Important note:**  
`.shape` is an attribute, **not a method**, so you don't use parentheses:
- **Correct**: `euro12.shape`
- **Wrong**: `euro12.shape()` ❌

**Accessing individual dimensions:**
- `euro12.shape[0]` → number of rows (16)
- `euro12.shape[1]` → number of columns (35)

**Use cases:**
- Quick check of dataset size
- Verify data loaded correctly
- Calculate total cells: rows × columns

In [ ]:
euro12.shape # Output ( 'Rows' , 'Columns' )

(16, 35)

**Expected Output:**
```
(16, 35)
```

This confirms we have 16 teams with 35 statistical categories each.

### Step 8. Display all column names

**Explanation:**  
`.columns` is an **attribute** that returns the column names of the DataFrame.

**Returns:**  
An `Index` object containing all column names as strings.

**Use cases:**
- See all available columns at a glance
- Check exact spelling of column names (important for filtering/selecting)
- Verify column order
- Copy column names for use in code

**Related operations:**
- `list(euro12.columns)` → Convert to a Python list
- `euro12.columns.tolist()` → Another way to convert to list
- `len(euro12.columns)` → Count number of columns

**Why this matters:**
- Column names are case-sensitive: 'Team' ≠ 'team'
- Some column names contain spaces: 'Shots on target'
- Knowing exact names prevents errors in filtering and selection

In [ ]:
euro12.columns # Returns ALL the column names of the DataFrame

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

**Expected Output:**
```
Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored',
       'Headed goals', 'Passes', 'Passes completed', 'Passing Accuracy',
       'Touches', 'Crosses', 'Dribbles', 'Corners Taken', 'Tackles',
       'Clearances', 'Interceptions', 'Clearances off line', 'Clean Sheets',
       'Blocks', 'Goals conceded', 'Saves made', 'Saves-to-shots ratio',
       'Fouls Won', 'Fouls Conceded', 'Offsides', 'Yellow Cards', 'Red Cards',
       'Subs on', 'Subs off', 'Players Used'],
      dtype='object')
```

Notice some columns have spaces in their names, which is common in datasets but can make selection trickier.

### Step 9. Display a subset of columns (excluding last 3)

**Explanation:**  
`.iloc[]` is used for **integer position-based** column selection.

**Breaking down the code:**  
`euro12.iloc[:, 0:-3]`

1. **`:`** (before comma) - **Row selector**:
   - Select **all rows**
   - Empty slice means "from start to end"

2. **`,`** - Separator between rows and columns

3. **`0:-3`** (after comma) - **Column selector**:
   - `0` = start from the **first column** (index 0)
   - `-3` = go up to (but **not including**) the **3rd column from the end**
   - This **excludes the last 3 columns**

**What gets excluded:**
- Column 32: 'Subs on'
- Column 33: 'Subs off'
- Column 34: 'Players Used'

**Result:**  
Shows all 16 teams with columns 0 through 31 (32 columns total, since 35 - 3 = 32)

**Understanding negative indexing:**
- `-1` = last column
- `-2` = second-to-last column
- `-3` = third-to-last column
- `0:-3` = "from first column up to (not including) third-to-last"

**Alternative ways to accomplish the same:**
- `euro12.iloc[:, :32]` - Explicitly select first 32 columns
- `euro12.drop(columns=['Subs on', 'Subs off', 'Players Used'])` - Drop by name
- `euro12[euro12.columns[:-3]]` - Using column names with slicing

**When to use `.iloc[]` for columns:**
- When you know the position but not the name
- When selecting ranges of columns
- When working with dynamic column positions

In [ ]:
euro12.iloc[:, 0:-3] # Excluding last 3 columns

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0

In [ ]:
euro12.iloc[:, :32] # For iLoc[ Start row:Finish row , Start column:Finish column]
            # ' : = 0:0 '

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0

**Expected Output:**
```
                  Team  Goals  Shots on target  ... Yellow Cards  Red Cards
0              Croatia      4               13  ...            9          0
1       Czech Republic      4               13  ...            7          0
2              Denmark      4               10  ...            4          0
3              England      5               11  ...            5          0
4               France      3               22  ...            6          0
5              Germany     10               32  ...            4          0
6               Greece      5                8  ...            9          1
7                Italy      6               34  ...           16          0
8          Netherlands      2               12  ...            5          0
9               Poland      2               15  ...            7          1
10            Portugal      6               22  ...           12          0
11 Republic of Ireland      1                7  ...            6          1
12              Russia      5                9  ...            6          0
13               Spain     12               42  ...           11          0
14              Sweden      5               17  ...            7          0
15             Ukraine      2                7  ...            5          0

[16 rows × 32 columns]
```

Note: The output shows 32 columns instead of 35, confirming the last 3 were excluded.

---
## Advanced Filtering: Working with Multiple Teams

### Step 10. Present only the Shooting Accuracy from England, Italy and Russia

**Explanation:**  
This combines multiple pandas techniques to filter specific rows and columns.

**Breaking down the code:**  
`euro12.loc[euro12.Team.isin(['England', 'Italy', 'Russia']), ['Shooting Accuracy']]`

**Part 1: Row filtering with `.isin()`**  
`euro12.Team.isin(['England', 'Italy', 'Russia'])`

- **`.isin()`** checks if each value in 'Team' column is in the provided list
- Returns a **boolean mask** (True/False for each row)
- True for rows where Team is 'England', 'Italy', or 'Russia'
- False for all other teams

**Why use `.isin()` instead of multiple conditions?**

**Without `.isin()` (verbose):**
```python
(euro12['Team'] == 'England') | (euro12['Team'] == 'Italy') | (euro12['Team'] == 'Russia')
```

**With `.isin()` (concise):**
```python
euro12['Team'].isin(['England', 'Italy', 'Russia'])
```

**Benefits of `.isin()`:**
- Much shorter and more readable
- Works with any number of values
- More efficient for many values
- Less error-prone (no need to remember `|` operators)

**Part 2: Using `.loc[]` for combined selection**  
`euro12.loc[row_condition, column_list]`

- **Before comma**: Row selector (the boolean mask from `.isin()`)
- **After comma**: Column selector (`['Shooting Accuracy']`)
- Returns only the intersection: selected rows × selected columns

**Part 3: Column selection**  
`['Shooting Accuracy']`

- Must be a **list**, even for a single column
- **With brackets** `['Shooting Accuracy']` → Returns a DataFrame
- **Without brackets** `'Shooting Accuracy'` → Would return a Series

**Result:**  
A DataFrame with:
- **3 rows** (England, Italy, Russia)
- **1 column** (Shooting Accuracy)

**Alternative syntax using bracket notation:**
```python
euro12[euro12['Team'].isin(['England', 'Italy', 'Russia'])][['Shooting Accuracy']]
```
This works but `.loc[]` is preferred for clarity and to avoid chained indexing warnings.

In [25]:
acierto_disparo = euro12.loc[euro12.Team.isin(['England', 'Italy', 'Russia']), ['Shooting Accuracy']]
acierto_disparo

   Shooting Accuracy
3              50.0%
7              43.0%
12             22.5%

**Expected Output:**
```
   Shooting Accuracy
3              50.0%
7              43.0%
12             22.5%
```

**Interpretation:**
- Row 3 (England): 50.0% shooting accuracy
- Row 7 (Italy): 43.0% shooting accuracy  
- Row 12 (Russia): 22.5% shooting accuracy

**Note:** The index numbers (3, 7, 12) are preserved from the original DataFrame, showing which rows these teams were in.

---
## Summary: Key Concepts Learned

### Data Loading
- Loading CSV files directly from URLs
- No need to download files locally first
- Pandas handles HTTP requests automatically

### Display Options
- `pd.set_option('display.max_columns', None)` for showing all columns
- Useful for wide datasets
- Other options: max_rows, width, precision

### DataFrame Inspection
- `.head(n)` - First n rows
- `.tail(n)` - Last n rows
- `.info()` - Detailed structure information
- `.shape` - Dimensions (rows, columns)
- `.columns` - All column names

### Advanced Selection Techniques

**1. Position-based column slicing with `.iloc[]`:**
```python
df.iloc[:, 0:-3]  # All rows, columns except last 3
```
- Use negative indexing to count from the end
- Colon (`:`) means "all" for that dimension

**2. Multiple value filtering with `.isin()`:**
```python
df[df['column'].isin([value1, value2, value3])]
```
- Much cleaner than multiple OR conditions
- Works with any number of values
- More efficient and readable

**3. Combined row and column selection with `.loc[]`:**
```python
df.loc[row_condition, ['column1', 'column2']]
```
- Filter rows and columns in one operation
- First argument: row selector (boolean mask)
- Second argument: column selector (list of names)

### Comparison: `.loc[]` vs `.iloc[]`

| Feature | `.loc[]` | `.iloc[]` |
|---------|----------|----------|
| **Selection method** | Label-based | Position-based |
| **Row selection** | Index labels | Integer positions |
| **Column selection** | Column names | Integer positions |
| **Slicing** | Inclusive | Exclusive end |
| **Use case** | When you know names | When you know positions |

### Best Practices

1. **Use `.isin()` for multiple value filtering**
   - Cleaner than chaining OR conditions
   - More maintainable as lists grow

2. **Use `.loc[]` for combined selection**
   - Explicit about what you're selecting
   - Avoids chained indexing warnings
   - Better performance

3. **Set display options appropriately**
   - Show all columns for wide datasets during exploration
   - Reset or limit for cleaner output in production

4. **Always inspect your data first**
   - Use `.head()`, `.info()`, `.columns`
   - Understand structure before filtering
   - Check for missing values and data types

### Common Patterns

```python
# Filter multiple values
df[df['column'].isin([val1, val2, val3])]

# Select specific rows and columns
df.loc[condition, ['col1', 'col2']]

# Exclude last n columns
df.iloc[:, :-n]

# Select range of columns by position
df.iloc[:, start:end]
```

### Key Takeaways

- **`.isin()`** is your friend for filtering multiple values
- **`.loc[]`** is best for label-based selection
- **`.iloc[]`** is best for position-based selection
- **Negative indexing** (`-3`, `-1`) counts from the end
- **Display options** can make data exploration much easier
- **Always verify** your selections by checking shape and head