# Practice Exercises - Filtering and Sorting Data

## Dataset: Alcohol Consumption by Country

This dataset contains information about alcohol consumption across different countries.

**Columns:**
- `country`: Name of the country
- `beer_servings`: Average beer servings per person
- `spirit_servings`: Average spirit servings per person
- `wine_servings`: Average wine servings per person
- `total_litres_of_pure_alcohol`: Total litres of pure alcohol per person per year
- `continent`: Continent code (AF=Africa, AS=Asia, EU=Europe, NA=North America, OC=Oceania, SA=South America)

---

## Instructions for Students:

1. Read each exercise carefully
2. Try to solve it on your own first
3. Check the hints if you get stuck
4. Compare your solution with classmates
5. Ask the instructor if you need help

**Remember:** There are often multiple ways to solve the same problem in pandas!

---

## Part 1: Loading and Exploring Data

These exercises practice the basics of loading and inspecting DataFrames.

### Exercise 1: Import the necessary libraries

Import pandas and numpy with their standard aliases.

**Hint:** The standard aliases are `pd` and `np`.

In [2]:
# Your code here

import numpy as np
import pandas as pd

### Exercise 2: Load the dataset

Read the `drinks.csv` file and assign it to a variable called `drinks`.

**Hint:** Use `pd.read_csv()`. The file is in the current directory.

In [3]:
# Your code here

drinks= pd.read_csv('drinks.csv')

# Use the 2 bottom cells at the beggining of the Exercise to understand data

In [ ]:
drinks.shape #1

(193, 6)

In [ ]:
#2
pd.set_option('display.max_columns', None) #All columns displayed

### Exercise 3: Display the first 10 rows

Show the first 10 countries in the dataset.

**Hint:** Use the `.head()` method with an argument.

In [ ]:
# Your code here 
drinks.head(10) #3

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
6,Argentina,193,25,221,8.3,SA
7,Armenia,21,179,11,3.8,EU
8,Australia,261,72,212,10.4,OC
9,Austria,279,75,191,9.7,EU

### Exercise 4: Display the last 5 rows

Show the last 5 countries in the dataset.

**Hint:** Use the `.tail()` method.

In [6]:
# Your code here
drinks.tail(5)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

### Exercise 5: Get information about the DataFrame

Display detailed information about the dataset structure, data types, and missing values.

**Hint:** Use the `.info()` method.

In [7]:
# Your code here
drinks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       193 non-null    object
 1   beer_servings                 193 non-null    int64
 2   spirit_servings               193 non-null    int64
 3   wine_servings                 193 non-null    int64
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     170 non-null    object
dtypes: float64(1), int64(3), object(2)
memory usage: 9.2+ KB

### Exercise 6: Display the shape of the DataFrame

Find out how many rows and columns are in the dataset.

**Hint:** Use the `.shape` attribute (no parentheses!).

In [8]:
# Your code here
drinks.shape

(193, 6)

### Exercise 7: Display all column names

List all the column names in the dataset.

**Hint:** Use the `.columns` attribute.

In [9]:
# Your code here
drinks.columns

Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

### Exercise 8: How many countries are in the dataset?

Count the total number of countries (rows).

**Hint:** You can use `len()`, `.shape[0]`, or count the 'country' column.

In [47]:
# Your code here
len(drinks)

193

### Both UP & DOWN are valid to count elements

In [11]:
#Also works
drinks.shape[0]

193

---
## Part 2: Unique Values and Counting

These exercises practice finding unique values.

### Exercise 9: Display all unique continents

Show all the unique continent codes in the dataset.

**Hint:** Use `.unique()` on the 'continent' column.

In [48]:
drinks

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

In [12]:
# Your code here
drinks['continent'].unique()

array(['AS', 'EU', 'AF', nan, 'SA', 'OC'], dtype=object)

### Exercise 10: How many unique continents are there?

Count the number of unique continents.

**Hint:** Use `.nunique()` or `len()` combined with `.unique()`.

In [13]:
# Your code here
drinks['continent'].nunique()

#len(drinks['continent'].unique())

5

In [ ]:
len(drinks['continent'].unique()) ## THERE'S ACTUALLY 5!!!

6

### Not very useful

### Exercise 11: Count how many countries are in each continent

Display the number of countries per continent.

**Hint:** Use `.value_counts()` on the 'continent' column.

In [52]:
# Your code here
drinks['continent'].value_counts()

continent
AF    53
EU    45
AS    44
OC    16
SA    12
Name: count, dtype: int64

---
## Part 3: Sorting Data

These exercises practice sorting DataFrames.

### Exercise 12: Sort by beer servings (ascending)

Sort the DataFrame by beer servings from lowest to highest.

**Hint:** Use `.sort_values()` with the `by` parameter.

In [ ]:
# Your code here
drinks.sort_values('beer_servings' )

#SAME 

drinks.sort_values( by='beer_servings' )

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
40,Cook Islands,0,254,74,5.9,OC
79,Iran,0,0,0,0.0,AS
90,Kuwait,0,0,0,0.0,AS
97,Libya,0,0,0,0.0,AF
...,...,...,...,...,...,...
135,Poland,343,215,56,10.9,EU
65,Germany,346,117,175,11.3,EU
62,Gabon,347,98,59,8.9,AF
45,Czech Republic,361,170,134,11.8,EU
117,Namibia,376,3,1,6.8,AF

### Exercise 13: Sort by total alcohol consumption (descending)

Sort the DataFrame by total litres of pure alcohol from highest to lowest.

**Hint:** Use `.sort_values()` with `ascending=False`.

In [ ]:
# Your code here  #Could add 'by='
drinks.sort_values('total_litres_of_pure_alcohol', ascending=False) ##ascending= inverts the order

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
15,Belarus,142,373,42,14.4,EU
98,Lithuania,343,244,56,12.9,EU
3,Andorra,245,138,312,12.4,EU
68,Grenada,199,438,28,11.9,NaN
45,Czech Republic,361,170,134,11.8,EU
...,...,...,...,...,...,...
79,Iran,0,0,0,0.0,AS
90,Kuwait,0,0,0,0.0,AS
128,Pakistan,0,0,0,0.0,AS
97,Libya,0,0,0,0.0,AF
0,Afghanistan,0,0,0,0.0,AS

### Exercise 14: Sort by multiple columns

Sort the DataFrame by continent (ascending) and then by wine servings (descending).

**Hint:** Pass a list to the `by` parameter: `by=['col1', 'col2']` and use `ascending=[True, False]`.

In [61]:
# Your code here
drinks.sort_values(by=['continent', 'wine_servings']) #Double filtering
        # Two different tables. SEEMS like one big table truncated but it's not

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
27,Burundi,88,0,0,6.3,AF
56,Eritrea,18,0,0,0.5,AF
58,Ethiopia,20,3,0,0.7,AF
95,Lesotho,82,29,0,2.8,AF
97,Libya,0,0,0,0.0,AF
...,...,...,...,...,...,...
5,Antigua & Barbuda,102,128,45,4.9,NaN
11,Bahamas,122,176,51,6.3,NaN
144,St. Lucia,171,315,71,10.1,NaN
184,USA,249,158,84,8.7,NaN
32,Canada,240,122,100,8.2,NaN

In [18]:
drinks.sort_values(by=['continent', 'wine_servings'], ascending= False)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
6,Argentina,193,25,221,8.3,SA
185,Uruguay,115,35,220,6.6,SA
35,Chile,130,124,172,7.6,SA
132,Paraguay,213,117,74,7.3,SA
133,Peru,163,160,21,6.1,SA
...,...,...,...,...,...,...
54,El Salvador,52,69,2,2.2,NaN
69,Guatemala,53,69,2,2.2,NaN
74,Honduras,69,98,2,3.0,NaN
73,Haiti,1,326,1,5.9,NaN
122,Nicaragua,78,118,1,3.5,NaN

---
## Part 4: Simple Filtering

These exercises practice basic filtering with single conditions.

### Exercise 15: Find all European countries

Display all countries where the continent is 'EU'.

**Hint:** Use boolean indexing: `drinks[drinks['continent'] == 'EU']`.

In [ ]:
# Your code here
drinks[drinks['continent'] == 'EU'] #Individual filtering

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
1,Albania,89,132,54,4.9,EU
3,Andorra,245,138,312,12.4,EU
7,Armenia,21,179,11,3.8,EU
9,Austria,279,75,191,9.7,EU
10,Azerbaijan,21,46,5,1.3,EU
15,Belarus,142,373,42,14.4,EU
16,Belgium,295,84,212,10.5,EU
21,Bosnia-Herzegovina,76,173,8,4.6,EU
25,Bulgaria,231,252,94,10.3,EU
42,Croatia,230,87,254,10.2,EU
44,Cyprus,192,154,113,8.2,EU
45,Czech Republic,361,170,134,11.8,EU
48,Denmark,224,81,278,10.4,EU
57,Estonia,224,194,59,9.5,EU
60,Finland,263,133,97,10.0,EU
61,France,127,151,370,11.8,EU
64,Georgia,52,100,149,5.4,EU
65,Germany,346,117,175,11.3,EU
67,Greece,133,112,218,8.3,EU
75,Hungary,234,215,185,11.3,EU
76,Iceland,233,61,78,6.6,EU
81,Ireland,313,118,165,11.4,EU
83,Italy,85,42,237,6.5,EU
93,Latvia,281,216,62,10.5,EU
98,Lithuania,343,244,56,12.9,EU
99,Luxembourg,236,133,271,11.4,EU
105,Malta,149,100,120,6.6,EU
111,Monaco,0,0,0,0.0,EU
113,Montenegro,31,114,128,4.9,EU
120,Netherlands,251,88,190,9.4,EU
126,Norway,169,71,129,6.7,EU
135,Poland,343,215,56,10.9,EU
136,Portugal,194,67,339,11.0,EU
139,Moldova,109,226,18,6.3,EU
140,Romania,297,122,167,10.4,EU
147,San Marino,0,0,0,0.0,EU
151,Serbia,283,131,127,9.6,EU
155,Slovakia,196,293,116,11.4,EU
156,Slovenia,270,51,276,10.6,EU
160,Spain,284,157,112,10.0,EU
165,Sweden,152,60,186,7.2,EU
166,Switzerland,185,100,280,10.2,EU
170,Macedonia,106,27,86,3.9,EU
180,Ukraine,206,237,45,8.9,EU
182,United Kingdom,219,126,195,10.4,EU

### Exercise 16: Find countries with zero alcohol consumption

Display all countries where total litres of pure alcohol equals 0.

**Hint:** Filter where `total_litres_of_pure_alcohol == 0.0`.

In [20]:
# Your code here
drinks[drinks['total_litres_of_pure_alcohol'] == 0.0]

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
13,Bangladesh,0,0,0,0.0,AS
46,North Korea,0,0,0,0.0,AS
79,Iran,0,0,0,0.0,AS
90,Kuwait,0,0,0,0.0,AS
97,Libya,0,0,0,0.0,AF
103,Maldives,0,0,0,0.0,AS
106,Marshall Islands,0,0,0,0.0,OC
107,Mauritania,0,0,0,0.0,AF
111,Monaco,0,0,0,0.0,EU
128,Pakistan,0,0,0,0.0,AS
147,San Marino,0,0,0,0.0,EU
158,Somalia,0,0,0,0.0,AF

### Exercise 17: How many countries have zero alcohol consumption?

Count how many countries have 0 total litres of pure alcohol.

**Hint:** Filter first, then use `len()`, `.shape[0]`, or `.count()`.

In [ ]:
# Your code here
len(drinks[drinks['total_litres_of_pure_alcohol'] == 0.0]) #Measuring length of specific condition

13

### Both are valid. Working

In [ ]:
drinks[drinks['total_litres_of_pure_alcohol'] == 0.0].shape[0] #Same as len()

13

### Exercise 18: Find countries with more than 300 beer servings

Display all countries where beer servings are greater than 300.

**Hint:** Use the `>` operator in the filter condition.

In [ ]:
# Your code here
drinks[drinks['beer_servings'] > 300] #Specific condition

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
45,Czech Republic,361,170,134,11.8,EU
62,Gabon,347,98,59,8.9,AF
65,Germany,346,117,175,11.3,EU
81,Ireland,313,118,165,11.4,EU
98,Lithuania,343,244,56,12.9,EU
117,Namibia,376,3,1,6.8,AF
129,Palau,306,63,23,6.9,OC
135,Poland,343,215,56,10.9,EU
188,Venezuela,333,100,3,7.7,SA

---
## Part 5: Multiple Conditions (AND / OR)

These exercises practice filtering with multiple conditions.

### Exercise 19: Find African countries with more than 100 wine servings

Display countries that are in Africa AND have more than 100 wine servings.

**Hint:** Use `&` to combine conditions. Don't forget parentheses around each condition!

In [ ]:
# Your code here
drinks[(drinks['continent']== 'AF') & (drinks['wine_servings'] > 100)] # Double specific conditions

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
55,Equatorial Guinea,92,0,233,5.8,AF
148,Sao Tome & Principe,56,38,140,4.2,AF

### Exercise 20: Find countries with high beer OR high wine consumption

Display countries where beer servings > 300 OR wine servings > 300.

**Hint:** Use `|` (pipe) for OR logic. Remember the parentheses!

In [ ]:
# Your code here
drinks[(drinks['beer_servings'] > 300) | (drinks['wine_servings'] > 300)] #Double specific condition
                                    # With 'Or'

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
3,Andorra,245,138,312,12.4,EU
45,Czech Republic,361,170,134,11.8,EU
61,France,127,151,370,11.8,EU
62,Gabon,347,98,59,8.9,AF
65,Germany,346,117,175,11.3,EU
81,Ireland,313,118,165,11.4,EU
98,Lithuania,343,244,56,12.9,EU
117,Namibia,376,3,1,6.8,AF
129,Palau,306,63,23,6.9,OC
135,Poland,343,215,56,10.9,EU
136,Portugal,194,67,339,11.0,EU
188,Venezuela,333,100,3,7.7,SA

### Exercise 21: Find Asian countries with total alcohol > 5 litres

Display Asian countries with more than 5 litres of total pure alcohol consumption.

**Hint:** Combine `continent == 'AS'` AND `total_litres_of_pure_alcohol > 5`.

In [ ]:
# Your code here
drinks[(drinks['continent']== 'AS') & (drinks['total_litres_of_pure_alcohol'] > 5)] #Double specific condition with 'And'

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
85,Japan,77,202,16,7.0,AS
87,Kazakhstan,124,246,12,6.8,AS
92,Laos,62,0,123,6.2,AS
138,South Korea,140,16,9,9.8,AS
141,Russian Federation,247,326,73,11.5,AS
169,Thailand,99,258,1,6.4,AS

---
## Part 6: Using .isin() for Multiple Values

These exercises practice the `.isin()` method for cleaner filtering.

### Exercise 22: Find North American and South American countries

Display all countries from North America (NA) and South America (SA).

**Hint:** Use `.isin(['NA', 'SA'])` on the continent column.

In [ ]:
# Your code here
drinks[drinks['continent'].isin(['NA', 'SA'])] # Multiple specific condition

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
6,Argentina,193,25,221,8.3,SA
20,Bolivia,167,41,8,3.8,SA
23,Brazil,245,145,16,7.2,SA
35,Chile,130,124,172,7.6,SA
37,Colombia,159,76,3,4.2,SA
52,Ecuador,162,74,3,4.2,SA
72,Guyana,93,302,1,7.1,SA
132,Paraguay,213,117,74,7.3,SA
133,Peru,163,160,21,6.1,SA
163,Suriname,128,178,7,5.6,SA
185,Uruguay,115,35,220,6.6,SA
188,Venezuela,333,100,3,7.7,SA

### Exercise 23: Find specific countries

Display data for Spain, Portugal, and France.

**Hint:** Use `.isin()` on the 'country' column with a list of country names.

In [ ]:
# Your code here
drinks[drinks['country'].isin(['Spain','Portugal','France'])] # Specific multiple(3+) condition

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
61,France,127,151,370,11.8,EU
136,Portugal,194,67,339,11.0,EU
160,Spain,284,157,112,10.0,EU

### Exercise 24: Find countries NOT in Europe or Asia

Display countries that are NOT in Europe or Asia.

**Hint:** Use `~` (NOT operator) before `.isin()`: `~drinks['continent'].isin(['EU', 'AS'])`.

In [ ]:
# Your code here
drinks[~drinks['continent'].isin(['EU','As'])] #Wave symbol used for: 'Not'
    #Wave symbol

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
2,Algeria,25,0,14,0.7,AF
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
6,Argentina,193,25,221,8.3,SA
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

---
## Part 7: Column Selection with .loc[] and .iloc[]

These exercises practice selecting specific rows and columns.

### Exercise 25: Display only country and beer servings for European countries

Show the country name and beer servings for all European countries.

**Hint:** Use `.loc[]` with a row condition and a list of column names.

In [30]:
# Your code here
drinks.loc[drinks['continent'] == 'EU', ['continent', 'country', 'beer_servings']]
                                        #This way we can filter and only show the desired columns

    continent             country  beer_servings
1          EU             Albania             89
3          EU             Andorra            245
7          EU             Armenia             21
9          EU             Austria            279
10         EU          Azerbaijan             21
15         EU             Belarus            142
16         EU             Belgium            295
21         EU  Bosnia-Herzegovina             76
25         EU            Bulgaria            231
42         EU             Croatia            230
44         EU              Cyprus            192
45         EU      Czech Republic            361
48         EU             Denmark            224
57         EU             Estonia            224
60         EU             Finland            263
61         EU              France            127
64         EU             Georgia             52
65         EU             Germany            346
67         EU              Greece            133
75         EU             Hungary            234
76         EU             Iceland            233
81         EU             Ireland            313
83         EU               Italy             85
93         EU              Latvia            281
98         EU           Lithuania            343
99         EU          Luxembourg            236
105        EU               Malta            149
111        EU              Monaco              0
113        EU          Montenegro             31
120        EU         Netherlands            251
126        EU              Norway            169
135        EU              Poland            343
136        EU            Portugal            194
139        EU             Moldova            109
140        EU             Romania            297
147        EU          San Marino              0
151        EU              Serbia            283
155        EU            Slovakia            196
156        EU            Slovenia            270
160        EU               Spain            284
165        EU              Sweden            152
166        EU         Switzerland            185
170        EU           Macedonia            106
180        EU             Ukraine            206
182        EU      United Kingdom            219

### Exercise 26: Get the first 3 columns for the first 5 countries

Display the first 5 rows and first 3 columns using position-based indexing.

**Hint:** Use `.iloc[0:5, 0:3]` (remember: iloc is exclusive on the end!).

In [ ]:
# Your code here
drinks.iloc[0:5, 0:3] #Position based index

       country  beer_servings  spirit_servings
0  Afghanistan              0                0
1      Albania             89              132
2      Algeria             25                0
3      Andorra            245              138
4       Angola            217               57

### Exercise 27: Display all columns except the last one

Show all countries with all columns except 'continent'.

**Hint:** Use `.iloc[:, :-1]` to exclude the last column by position.

In [63]:
# Your code here
drinks.iloc[:, :-1] #-1 excludes the Last Column

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
...,...,...,...,...,...
188,Venezuela,333,100,3,7.7
189,Vietnam,111,2,1,2.0
190,Yemen,6,0,0,0.1
191,Zambia,32,19,4,2.5
192,Zimbabwe,64,18,4,4.7

### Exercise 28: Get wine servings for USA, Mexico, and Canada

Display only the wine servings column for these three countries.

**Hint:** Combine `.isin()` with `.loc[]` to select specific rows and columns.

In [ ]:
# Your code here
drinks.loc[drinks['country'].isin(['USA', 'Mexico', 'Canada']), ['country', 'wine_servings']] #loc['condition', 'Column display']
        #Loc[ ([Rows that you want to de shown]) , ([Columns that you want to be shown]) ]

    country  wine_servings
32   Canada            100
109  Mexico              5
184     USA             84

---
## Part 8: Finding Maximums and Minimums

These exercises practice finding extreme values.

### Exercise 29: Which country has the highest beer servings?

Find the country with the maximum beer servings.

**Hint:** Use `.loc[]` with `.idxmax()` or filter where `beer_servings == drinks['beer_servings'].max()`.

In [ ]:
# Your code here
drinks.loc[drinks['beer_servings'].idxmax(), 'country'] # idxmax() selects the max value of 'beer_servings', then displays country_name

'Namibia'

In [ ]:
drinks[drinks['beer_servings'] == drinks['beer_servings'].max()] #Full row display of Max value

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
117,Namibia,376,3,1,6.8,AF

### Exercise 30: What is the maximum value for beer servings?

Display just the number (not the whole row).

**Hint:** Use `.max()` on the beer_servings column.

In [ ]:
# Your code here
drinks['beer_servings'].max() #Simple max value of beer servings

376

### Exercise 31: Which country has the highest total alcohol consumption?

Find the country with the maximum total litres of pure alcohol.

**Hint:** Use `.loc[drinks['total_litres_of_pure_alcohol'].idxmax()]`.

In [65]:
# Your code here
drinks.loc[drinks['total_litres_of_pure_alcohol'].idxmax()]

country                         Belarus
beer_servings                       142
spirit_servings                     373
wine_servings                        42
total_litres_of_pure_alcohol       14.4
continent                            EU
Name: 15, dtype: object

### Exercise 32: Find the country with the lowest wine servings (excluding 0)

Find the country with the minimum wine servings, but only among countries that have wine servings > 0.

**Hint:** Filter first `drinks[drinks['wine_servings'] > 0]`, then find the minimum.

In [ ]:
# Your code here
drinks_with_no_wine = drinks[drinks['wine_servings'] > 0]   #Countries with more than 0 wine servings
drinks_with_no_wine = drinks_with_no_wine.loc[drinks_with_no_wine['wine_servings'].idxmin()] #Finding the minimum value of the group
drinks_with_no_wine #Printing

country                         Brunei
beer_servings                       31
spirit_servings                      2
wine_servings                        1
total_litres_of_pure_alcohol       0.6
continent                           AS
Name: 24, dtype: object

---
## Part 9: Statistical Operations

These exercises practice basic statistical calculations.

### Exercise 33: Calculate the mean beer servings

Find the average beer servings across all countries.

**Hint:** Use `.mean()` on the beer_servings column.

In [39]:
# Your code here
drinks['beer_servings'].mean()

np.float64(106.16062176165804)

### Exercise 34: Calculate the median total alcohol consumption

Find the median value for total litres of pure alcohol.

**Hint:** Use `.median()` on the appropriate column.

In [ ]:
# Your code here
drinks['beer_servings'].median()

76.0

### Exercise 35: Get summary statistics for all numeric columns

Display count, mean, std, min, 25%, 50%, 75%, and max for all numeric columns.

**Hint:** Use `.describe()` method.

In [ ]:
# Your code here
drinks.describe() #Used for quartiles

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
count,193.000000,193.000000,193.000000,193.000000
mean,106.160622,80.994819,49.450777,4.717098
std,101.143103,88.284312,79.697598,3.773298
min,0.000000,0.000000,0.000000,0.000000
25%,20.000000,4.000000,1.000000,1.300000
50%,76.000000,56.000000,8.000000,4.200000
75%,188.000000,128.000000,59.000000,7.200000
max,376.000000,438.000000,370.000000,14.400000

---
## Part 10: Challenge Exercises

These exercises combine multiple concepts. Try to solve them without looking at hints!

### Exercise 36: Find the top 5 countries by total alcohol consumption

Display the top 5 countries with the highest total litres of pure alcohol consumption.

**Hint:** Sort descending and use `.head(5)`.

In [42]:
# Your code here

### Exercise 37: Which continent has the highest average beer consumption?

Calculate the average beer servings for each continent and find which one is highest.

**Hint:** Use `.groupby('continent')['beer_servings'].mean()` and then `.sort_values()`.

In [43]:
# Your code here

### Exercise 38: Find European countries with above-average alcohol consumption

Display European countries where total alcohol consumption is above the European average.

**Hint:** 
1. Filter for European countries
2. Calculate the mean of total_litres_of_pure_alcohol for Europe
3. Filter European countries where consumption > European mean

In [44]:
# Your code here

### Exercise 39: Create a 'preference' column

Add a new column called 'preference' that indicates whether a country prefers 'beer', 'wine', or 'spirits' based on which has the highest servings.

**Hint:** This is advanced! You'll need to use `.idxmax(axis=1)` on the three serving columns.

In [45]:
# Your code here

### Exercise 40: Find countries where wine > beer AND wine > spirits

Display countries where wine servings are greater than both beer and spirit servings.

**Hint:** Combine three conditions with `&` operator.

In [46]:
# Your code here

---
## Bonus: Reflection Questions

Discuss these questions with your classmates or instructor:

1. **When should you use `.loc[]` vs `.iloc[]`?**
   - What are the key differences?
   - Can you give an example where each is better?

2. **Why is `.isin()` better than multiple OR conditions?**
   - Compare readability
   - Consider maintainability when you have 10+ values

3. **What are three different ways to count rows in a filtered DataFrame?**
   - Which one do you prefer and why?

4. **How do you debug when a filter returns no results?**
   - What steps would you take?
   - What are common mistakes?

5. **Why are parentheses important when using `&` and `|` operators?**
   - What happens if you forget them?
   - Try it and see!

---

## Great job completing these exercises! 🎉

Remember:
- Practice makes perfect
- There are multiple ways to solve most problems
- Don't hesitate to ask questions
- Check the documentation when stuck: `help(function)` or `function?` in Jupyter

**Next steps:**
- Compare your solutions with classmates
- Try solving exercises in different ways
- Ask your instructor to review your code
- Practice with other datasets!